### ISSUE TITLE
question about getting VOC20072012trainval dataset

### ISSUE THREAD

**Issue by michaelku1** [amazon-research/omni-detr#2]
Thanks for the amazing work. As stated above, I was wondering if the combined dataset can be obtained from the official site directly or is there a .txt file that can be used to parse it? Thanks.

**Comment by peiwang062** [comment]
I think just using something like cp VOC2007trainval/JPEGImages/* VOC20072012trainval/JPEGImages to build VOC20072012trainval folder.

**Comment by michaelku1** [comment]
I see, so just concat both folders, Thanks a lot.
