### ISSUE TITLE
Which model should I use after training, the teacher or the student?

### ISSUE THREAD

**Issue by 1224wxwx** [amazon-research/omni-detr#5]
Thanks for the amazing work. 
After training for several epochs in SSOD mode，I found that the performance of teacher model was much better than student.
I wonder whether this phenomena is normal or not? If it is normal, which model should I use，the teacher or the sutdent？
Thanks.

**Comment by zhaoweicai** [comment]
Yes, the gap between student and teacher is normal, and we used the results of the teacher in the papers.

**Comment by 1224wxwx** [comment]
thank you
